### ISSUE TITLE
subuid and subgid values why 1000000:1000000000?

### ISSUE THREAD

**Issue by thepenguinthatwants** [corneliusweig/kubernetes-lxd#8]
Your repo is awsome as using lxd to test and learn kubernetes feels much more efficient than minikube. Tho I am just now only starting and wondering few things.

In arch linux it was recommended to use

/etc/subuid
root:100000:65536
/etc/subgid
root:100000:65536

but in your guide its
1000000:1000000000
Can you elaborate why?

**Comment by corneliusweig** [comment]
No, this was an arbitrary choice because I thought it does not matter. Apparently I was wrong :). #7 corrects this error.
